#!/bin/bash
if [[ ! -d "fonts" ]]; then
    mkdir fonts
fi
cd fonts
chmod +x ../scripts/build.py
../scripts/build.py
cd ..
#git stash
#git rebase origin/master
#git stash pop
git add svgs
git add fonts
git status
if [[ $# -gt 0 ]]; then
    message=$*
else
    message="Built fonts"
fi
echo $message
git commit -m "$message"
git push
